language: php
php:
  - 5.4
before_install:
  - sudo apt-get install -y nodejs npm # php5-fpm nginx
  - npm install -g grunt-cli
  - npm install -g casperjs
before_script:
#  - sh setupfpmnginx.sh
  - mysql -e "create database aloja2;" -uroot
  - mysql -uroot aloja2 < db_schema.sql
  - php -S localhost:8080 --docroot=aloja-web &
  - sleep 3
install:
  - npm install
  - cd aloja-web && php composer.phar self-update && php composer.phar update && cd ..
script: bash tests.sh
services: mysql
notifications:
  email: false
