# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  #Default base image to build from scratch
  #config.vm.box = "hashicorp/precise64"
  #Prebuilt box for ALOJA
  config.vm.box = "npoggi/aloja-precise64"

  #config.vm.box = "yungsang/coreos"
  #
  #config.vm.provision "docker" do |d|
  #  d.build_dir "."
  #  #d.build_image "/vagrant/app"
  #end

  config.vm.host_name = "vagrant"

  #web document root
  config.vm.synced_folder "../", "/vagrant/workspace"

  #bash scripts
  config.vm.provision :shell, :path => "bootstrap.sh"

  #puppet config
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "puppet/modules"
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "init.pp"
    #puppet.options = "--verbose --debug"
  end

  #net ports
  config.vm.network :forwarded_port, host: 8080, guest: 80 #web
  config.vm.network :forwarded_port, host: 4306, guest: 3306 #mysql

end
