#on previous versions it does not download the image automatically
Vagrant.require_version ">= 1.6"

VAGRANTFILE_API_VERSION = "2"

#avoids having to $ vagrant up --provider docker
#ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #for Virtualbox (Default)
  config.vm.provider 'virtualbox' do |v|
    #Default base image to build from scratch
    #config.vm.box = "hashicorp/precise64"
    #Prebuilt box for ALOJA
    config.vm.box = "npoggi/aloja-precise64"

    v.memory = 2048 #change as needed
    v.cpus = 1
  end

  #for Docker (optional, but faster on Linux)
  config.vm.provider 'docker' do |d, override|
    override.vm.box = nil #Vagrant gets confused with the Virtualbox name
    #use a prebuilt image ie 'npoggi/vagrant-docker:latest'
    if ENV['DOCKER_IMAGE'] then
      print "Using docker image " + ENV['DOCKER_IMAGE'] + " (downloads if necessary)\n"
      d.image = ENV['DOCKER_IMAGE']
    else
      #build from the Dockerfile
      d.build_dir = '.'
      d.name = 'aloja-vagrant-docker'
    end
    #the docker image must remain running for SSH (See the Dockerfile)
    d.has_ssh = true
  end

  #web document root
  config.vm.synced_folder "../", "/vagrant/workspace"
  config.vm.synced_folder "../aloja-web/logs", "/vagrant/workspace/aloja-web/logs", :owner=> 'www-data', :mount_options => ["dmode=775", "fmode=664"]
  config.vm.synced_folder "../aloja-web/cache", "/vagrant/workspace/aloja-web/cache", :owner=> 'www-data', :mount_options => ["dmode=775", "fmode=664"]

  #bash scripts
  config.vm.provision :shell, :path => "bootstrap.sh"

  # default box (aloja-web)
  config.vm.define "default", primary: true do |default|

    #puppet config
    default.vm.provision "puppet" do |puppet|
      puppet.module_path = "puppet/modules"
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "init.pp"
      puppet.options = "--environment dev" 
      #puppet.options = "--verbose --debug"
    end

    #net ports
    default.vm.network :forwarded_port, host: 8080, guest: 80 #web
    default.vm.network :forwarded_port, host: 4306, guest: 3306 #mysql
    default.vm.network :forwarded_port, host: 3307, guest: 3307 #mysql prod

  end

  # cluster nodes for benchmarking (aloja-deploy)
  config.vm.define "vagrant1", autostart: false do |node|
    node.vm.hostname = "vagrant1"
    node.vm.network "private_network", ip: "10.42.42.101"
    node.vm.provision "shell", path: "files/vagrant_cluster/provision.sh"
    node.vm.network :forwarded_port, host: 19888, guest: 19888 #history server
    node.vm.network :forwarded_port, host: 8088, guest: 8088 #resource manager
  end
  config.vm.define "vagrant2", autostart: false do |node|
    node.vm.hostname = "vagrant2"
    node.vm.network "private_network", ip: "10.42.42.102"
    node.vm.provision "shell", path: "files/vagrant_cluster/provision.sh"
  end

end
