VAGRANTFILE_API_VERSION = "2"

#avoids having to $ vagrant provider=docker
#ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #Default base image to build from scratch
  #config.vm.box = "hashicorp/precise64"
  #Prebuilt box for ALOJA
  config.vm.box = "npoggi/aloja-precise64"
  config.vm.host_name = "vagrant"

  config.vm.provider 'docker' do |d|
    #use a prebuilt image ie 'npoggi/vagrant-docker:latest'
    if ENV['DOCKER_IMAGE'] then
      print 'Using docker image ' + ENV['DOCKER_IMAGE'] +' (downloads if necessary)\n'
      d.image = ENV['DOCKER_IMAGE']
    else
      #build from the Dockerfile
      print 'Building from the Dockerfile (if necessary)\n'
      d.build_dir = '.'
      d.name = 'vagrant-docker'
    end
    #the docker image must remain running for SSH (See the Dockerfile)
    d.has_ssh = true
  end

  #web document root
  config.vm.synced_folder "../", "/vagrant/workspace"
  config.vm.synced_folder "../aloja-web/logs", "/vagrant/workspace/aloja-web/logs", :owner=> 'www-data', :mount_options => ["dmode=775", "fmode=664"]

  #bash scripts
  config.vm.provision :shell, :path => "bootstrap.sh"

  #puppet config
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "puppet/modules"
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "init.pp"
    puppet.options = "--environment dev"
    #puppet.options = "--verbose --debug"
  end

  #net ports
  config.vm.network :forwarded_port, host: 8080, guest: 80 #web
  config.vm.network :forwarded_port, host: 4306, guest: 3306 #mysql

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
