#!/bin/sh
# ------------------------------------------------------------------------
# vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 textwidth=75   :
# ------------------------------------------------------------------------
# This is the global configuration file for the ssh-tunnel utility. It's :
# "sourced" by that tool, so one can use basic shell commands here.      :
# ------------------------------------------------------------------------

# Configuration that differs between root and regular users
if [ "x$USER" = "xroot" -o "x`whoami`" = "xroot" ]; then
    # Where to find gobal configuration files
    : ${SSH_TUNNEL_CONFIG:="/etc/ssh-tunnel"}
    # Where to find private SSH-keys to be used by default
    : ${SSH_TUNNEL_KEY_DIR:="$SSH_TUNNEL_CONFIG/keys-enabled"}
    # Where to find the list of tunnels to create
    : ${SSH_TUNNEL_GROUP_DIR:="$SSH_TUNNEL_CONFIG/groups-enabled"}
    # Where to store runtime data
    : ${SSH_TUNNEL_RUNTIME_DIR:="/var/run/ssh-tunnel"}
    # Where to store logging information
    : ${SSH_TUNNEL_LOG:="/var/log/ssh-tunnel.log"}
else
    # Ensure $USER and $HOME are defined
    : ${USER:="`whoami`"}; : ${HOME:="/home/$USER"}
    # Where to find per-user configuration files
    : ${SSH_TUNNEL_CONFIG:="$HOME/.ssh/tunnel"}
    # Where to find private SSH-keys to be used by default
    : ${SSH_TUNNEL_KEY_DIR:="$SSH_TUNNEL_CONFIG/keys.d"}
    # Where to find the list of tunnels to create
    : ${SSH_TUNNEL_GROUP_DIR:="$SSH_TUNNEL_CONFIG/groups.d"}
    # Where to store runtime data
    : ${SSH_TUNNEL_RUNTIME_DIR:="/tmp/ssh-tunnel.$USER"}
    # Where to store logging information
    : ${SSH_TUNNEL_LOG:="$SSH_TUNNEL_RUNTIME_DIR/tunnel.log"}
fi

# Where to store the SSH_AUTH_SOCK
: ${SSH_TUNNEL_AUTH_SOCK:="$SSH_TUNNEL_RUNTIME_DIR/auth.sock"}
# Where to store the SSH_AGENT_PID
: ${SSH_TUNNEL_AGENT_PID_FILE:="$SSH_TUNNEL_RUNTIME_DIR/agent.pid"}
    
# The name of the autossh(1) executable
: ${SSH_TUNNEL_AUTOSSH:="autossh"}
# The name of the ssh-agent(1) executable
: ${SSH_TUNNEL_SSH_AGENT:="ssh-agent"}
# The name of the ssh-add(1) executable
: ${SSH_TUNNEL_SSH_ADD:="ssh-add"}

# Additional parameters for autossh(1)
: ${SSH_TUNNEL_AUTOSSH_OPTS:=""}

# ------------------------------------------------------------------------
# Specific to autossh(1): The options below are specific to the SSH      :
# handler used by ssh-tunnel. They may differ in the local version, so   :
# please refer to the system's manual page. In fact, even the prepared   :
# section below has been taken from Debian's version of the manual..     :
# Please note that AUTOSSH_PIDFILE and AUTOSSH_LOGFILE are not handled   :
# here. The latter, however, can be configured with SSH_TUNNEL_LOG       :
# ------------------------------------------------------------------------

# If this variable is set, the logging level is set to to
# LOG_DEBUG, and if the operating system supports it, syslog is set
# to duplicate log entries to stderr.
#AUTOSSH_DEBUG=
#export AUTOSSH_DEBUG

# Specifies the time to wait before the first connection test.
# Thereafter the general poll time is used (see AUTOSSH_POLL
# below).
#AUTOSSH_FIRST_POLL=
#export AUTOSSH_FIRST_POLL

# Specifies how long ssh must be up before we consider it a suc‐
# cessful connection. The default is 30 seconds. Note that if
# AUTOSSH_GATETIME is set to 0, then not only is the gatetime be‐
# haviour turned off, but autossh also ignores the first run fail‐
# ure of ssh. This may be useful when running autossh at boot.
#AUTOSSH_GATETIME=
#export AUTOSSH_GATETIME

# Specifies the log level, corresponding to the levels used by sys‐
# log; so 0-7 with 7 being the chattiest.
#AUTOSSH_LOGLEVEL=
#export AUTOSSH_LOGLEVEL

# Sets the maximum number of seconds that the program should run.
# Once the number of seconds has been passed, the ssh child will be
# killed and the program will exit.
#AUTOSSH_MAXLIFETIME=
#export AUTOSSH_MAXLIFETIME

# Specifies how many times ssh should be started. A negative number
# means no limit on the number of times ssh is started. The default
# value is -1.
#AUTOSSH_MAXSTART=
#export AUTOSSH_MAXSTART

# Append message to echo message sent when testing connections.
#AUTOSSH_MESSAGE=
#export AUTOSSH_MESSAGE

# Specifies the path to the ssh executable, in case it is different
# than the path compiled in.
#AUTOSSH_PATH=
#export AUTOSSH_PATH

# Specifies the connection poll time in seconds; default is 600
# seconds.  If the poll time is less than twice the network time‐
# outs (default 15 seconds) the network timeouts will be adjusted
# downward to 1/2 the poll time.
#AUTOSSH_POLL=
#export AUTOSSH_POLL

# Sets the connection monitoring port. Mostly in case ssh appropri‐
# ates -M at some time. But because of this possible use,
# AUTOSSH_PORT overrides the -M flag. A value of 0 turns the moni‐
# toring function off.
#AUTOSSH_PORT=
#export AUTOSSH_PORT

