#DO NOT re-commit this file, should be under .gitignore

#Account and keys
subscription_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' #Your subscription ID
mgmt_certificate: 'keys/mgmkey.pem'

ssh_private_key_file: 'keys/management.key'
ssh_certificate_file: 'keys/management.cer'

#users
vm_user: 'vagrant'
vm_password: 'yOur_$ecured_p4s$word'

ssh_port: '22'

#Account settings
vm_name: 'vagrantbox' #MUST BE LOWER CASE! https://github.com/MSOpenTech/vagrant-azure/issues/11
storage_acct_name: 'vagrantboxes'
cloud_service_name: 'vagrantboxes'
deployment_name: 'vagrantboxes'
vm_location: 'West Europe' # e.g., West US
vm_size: 'Small'
tcp_endpoints: '80:80' #Guest port: 80, public port: 80

#Ubuntu 12_04
vm_image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB'
#Ubuntu 14_04
#vm_image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140416.1-en-us-30GB'
