mysql_user: root
mysql_pwd:
db_conn_chain: "mysql:host=localhost;dbname=aloja2"
#Prod MySQL, need to SSH first in Vagrant VM with: ssh -L localhost:3307:host:3306 prod_user@prod_server
#db_conn_chain: "mysql:host=127.0.0.1;dbname=aloja2;port=3307"
db_cache_path: "cache/query"
in_cache: true
enable_debug: true
twig_cache_path: "cache/twig"
twig_views_path: "views/"
#Show PHP warnings?
show_warnings: false

protected_urls: { "/": "", "/bestconfig": "", "/metrics": "" }
protected_user: pristine
protected_pass: pristine2014
