mysql_user: mlread
mysql_pwd: mlr34d
db_conn_chain: "mysql:host=127.0.0.1;port=3307;dbname=aloja2"
#Prod MySQL, need to SSH first in Vagrant VM with: ssh -L localhost:3307:gallactica:3306 user@minerva.bsc.es
#db_conn_chain: "mysql:host=104.40.140.48;dbname=aloja2;port=3307"
db_cache_path: "cache/query"
in_cache: false
enable_debug: true
twig_cache_path: "cache/twig"
twig_views_path: "views/"
