mysql_user: vagrant
mysql_pwd: vagrant
db_conn_chain: "mysql:host=localhost;dbname=aloja2"
#Prod MySQL, need to SSH first in Vagrant VM with: ssh -L localhost:3307:gallactica:3306 user@minerva.bsc.es
#db_conn_chain: "mysql:host=127.0.0.1;dbname=aloja2;port=3307"
db_cache_path: "/tmp"
in_cache: false
enable_debug: false
