paths:
    migrations: %%PHINX_CONFIG_DIR%%/../migrations

environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8

    development:
        adapter: mysql
        host: 127.0.0.1
        name: aloja2
        user: vagrant
        pass: 'vagrant'
        port: 4306
        charset: utf8

    vagrant:
        adapter: mysql
        host: localhost
        name: aloja2
        user: vagrant
        pass: 'vagrant'
        port: 3306
        charset: utf8
